services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - proxynet

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - breeder_profiles:/app/public/uploads/breeder-profiles
      - profile_pictures:/app/public/uploads/profile-pictures
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - proxynet

networks:
  proxynet:
    external: true

volumes:
  breeder_profiles:
    driver: local
  profile_pictures:
    driver: local