services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - proxynet

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - uploads_data:/app/public/uploads
    networks:
      - proxynet

networks:
  proxynet:
    external: true

volumes:
  uploads_data:
    driver: local
