services:
  alp:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - ./server/public/uploads:/app/public/uploads
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-4000}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - HAS_NOTIFY_URL=${HAS_NOTIFY_URL}
      - HAS_TOKEN=${HAS_TOKEN}
